### ISSUE TITLE
Unable to import image

### ISSUE THREAD

**Issue by LivelyCarpet87** [evuksani/PyCarver#1]
When I import image, I recieve:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "main.py", line 540, in openDiskImage
    diskImageOut = Popen([self.mmlsPath, diskImageLocation], stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/mmls': '/usr/bin/mmls'

**Comment by evuksani** [comment]
You don't have mmls installed or it's not in the correct directory. Can you check that it's actually installed on your end?
